remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
url: 'https://iqbalriiaz.github.io/' # your main domain
baseurl: 'seu-researchers/' # if you're using custom domain keep this blank example: baseurl: ''
darkmode: true
